services:
  hub-bot:
    build: .
    image: the-hub-bot:latest
    container_name: the-hub-bot
    restart: unless-stopped

    labels:
      com.katrin.logs.app: "hub-bot"
      com.katrin.logs.environment: "production"

    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
