"""create feedback table

Revision ID: 5720a0285f36
Revises: 8ed412f6c9a5
Create Date: 2026-08-01 19:48:23.248784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5720a0285f36'
down_revision: Union[str, Sequence[str], None] = '8ed412f6c9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, server_default='new'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_app_id'), 'feedback', ['app_id'], unique=False)
    op.create_index(op.f('ix_feedback_telegram_id'), 'feedback', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_telegram_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_app_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
